### PR TITLE
2.2 release merge

### PR DESCRIPTION
**Pull request by tarzzz**
@chriddyp Please review..

cc: @scjody .

### CODE REVIEW

**Comment by chriddyp** [comment]
@tarzzz - this was already added to master earlier in https://github.com/plotly/plotly-database-connector/commit/458cc1b9aa68c324389b8f7a9bda48cec6f5a349

I guess this keeps things consistent though?

**Comment by tarzzz** [comment]
@chriddyp Yes, this brings `master` and `2.2-release` in sync.. I am going to test master on my local system after this merge to confirm that everything works okay..

**Comment by tarzzz** [comment]
@chriddyp 💃  ??

**Comment by chriddyp** [comment]
💃

**Pull request merged**
