### PR TITLE
Yarn and Fix Builds

### PR DESCRIPTION
**Pull request by chriddyp**
Attempting builds on Yarn instead of NPM. See #161 for some more details.

### CODE REVIEW

**Comment by chriddyp** [comment]
CircleCI and my Mac are now installing things OK, but the Windows AppVeyor is failing:
```
C:\projects\plotly-database-connector\node_modules\libpq\build\Release\addon.node : fatal error LNK1120: 43 unresolved externals [C:\projects\plotly-database-connector\node_modules\libpq\build\addon.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\plotly-database-connector\node_modules\libpq
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by chriddyp** [comment]
builds are now building but the windows build isn't working on my parallel's machine
image

**Comment by chriddyp** [comment]
I haven't actually tested the Dockerfile myself, but I made the appropriate changes. @tarzzz - we'll have to test this Dockerfile for the next on-prem build.

**Comment by chriddyp** [comment]
lol these checkboxes are huge on windows
image

**Comment by jackparmer** [comment]
💃 Thanks for figuring this out!

**Pull request merged**
