### PR TITLE
Add an option to disable certificate validation

### PR DESCRIPTION
**Pull request by chriddyp**
If running on the same machine as plotly on-premise,
 then we do not need to verify SSL certificates as
 requests to plotly will never leave the server.

 This is to allow users to use Plotly On-Prem with
 a self-signed certificate generated by replicated
 or by themselves without actually specifying the
 path of the actual certificate.
 See https://github.com/plotly/streambed/issues/8948.

 Note: if any requests are made to other domains
 or if any other services end up running inside
 this docker container, then this setting should
 be applied on a request-by-request basis as an
 argument of the `fetch` `agent` instead of
 set as a process variable.

cc @scjody @alexandresobolevski

### CODE REVIEW

**Comment by chriddyp** [comment]
I haven't really tested this yet.

**Comment by chriddyp** [comment]
Getting some issues running this locally for some reason:
```
$ ./dist/headless-bundle.js
Error: Unable to parse.
```

**Comment by chriddyp** [comment]
@alexandresobolevski I can't seem to get my local environment working. Could you wrap this one up? Need to verify the following things:

- [ ] Manually test that this works locally
- [ ] Run this locally inside a docker container against prod. Manually test that persistent connections work against a new user.

To run this locally as a docker container, do:
```
$ docker build -t database-connector .
$ PLOTLY_DOMAIN_API="api.plot.ly" PLOTLY_STREAMBED_SSL_ENABLED="true" docker run -p 9494:9494 -v ~/.plotly/connector:/home -e PLOTLY_CONNECTOR_PLOTLY_API_DOMAIN=$PLOTLY_DOMAIN_API -e PLOTLY_CONNECTOR_PLOTLY_API_SSL_ENABLED=$PLOTLY_STREAMBED_SSL_ENABLED PLOTLY_CONNECTOR_STORAGE_PATH="/home" -d database-connector
```

- [ ] Run this locally as a docker container against this test on-premise server:  https://chrisp.plot.ly without the `PLOTLY_CONNECTOR_IS_RUNNING_IN_ON_PREM` argument. Plotly should _fail_ in the oauth flow.
```
$ PLOTLY_DOMAIN_API="chrisp.plot.ly" PLOTLY_STREAMBED_SSL_ENABLED="true" docker run -p 9494:9494 -v ~/.plotly/connector:/home -e PLOTLY_CONNECTOR_PLOTLY_API_DOMAIN=$PLOTLY_DOMAIN_API -e PLOTLY_CONNECTOR_PLOTLY_API_SSL_ENABLED=$PLOTLY_STREAMBED_SSL_ENABLED PLOTLY_CONNECTOR_STORAGE_PATH="/home" -d database-connector
```

- [ ] Re-run as a docker container with the command line argument `PLOTLY_CONNECTOR_IS_RUNNING_INSIDE_ON_PREM="true"` against the test on-prem server (https://chrisp.plot.ly ). Contrary to before, Plotly should not fail when "logging in" to the connector from the workspace and when scheduling a query. The command-line argument to run is: 
```
$ PLOTLY_DOMAIN_API="chrisp.plot.ly" PLOTLY_STREAMBED_SSL_ENABLED="true" docker run -p 9494:9494 -v ~/.plotly/connector:/home -e PLOTLY_CONNECTOR_PLOTLY_API_DOMAIN=$PLOTLY_DOMAIN_API -e PLOTLY_CONNECTOR_PLOTLY_API_SSL_ENABLED=$PLOTLY_STREAMBED_SSL_ENABLED PLOTLY_CONNECTOR_STORAGE_PATH="/home" -d database-connector
```

Note that when you test this against on-prem, you'll need to specify the `http://localhost:9494` instead of using the connector that is already installed on the on-prem instance (https://chrisp.plot.ly/external-data-connector).

See https://github.com/plotly/streambed/issues/8948 for more details.

**Comment by alexandresobolevski** [comment]
@chriddyp Reminder that using the `$` did not work for me setting environment variables in a docker container. The commands were thus
```
$ docker run \
-p 9494:9494 \
-v ~/.plotly/connector:/home \
-e PLOTLY_CONNECTOR_PLOTLY_API_DOMAIN="chrisp.plot.ly"\
-e PLOTLY_CONNECTOR_PLOTLY_API_SSL_ENABLED="true" \
-e PLOTLY_CONNECTOR_STORAGE_PATH="/home" \
-d database-connector
```

and

```
docker run \
-p 9494:9494 \
-v ~/.plotly/connector:/home \
-e PLOTLY_CONNECTOR_PLOTLY_API_DOMAIN="chrisp.plot.ly"\
-e PLOTLY_CONNECTOR_PLOTLY_API_SSL_ENABLED="true" \
-e PLOTLY_CONNECTOR_IS_RUNNING_INSIDE_ON_PREM="true"
-e PLOTLY_CONNECTOR_STORAGE_PATH="/home" \
-d database-connector
```

<i> Also note to self: To run agains `chrisp.plot.ly` need to add this host to `CORS_ALLOWED_ORIGINS` setting. The defaults are `plot.ly`, along with its stage and local.</i>

**Pull request merged**
